steps:
  - id: 'branch name'
    name: 'alpine'
    entrypoint: 'sh'
    dir: 'terraform'

    # env:
    #   - 'BRANCH_NAME=${_BRANCH_NAME}'
    args:
    - '-c'
    - |
        echo  "Branch name is $BRANCH_NAME"

  - id: 'tf init'
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: 'sh'
    dir: 'terraform'
    args:
    -  '-c'
    -  |
        terraform init

  - id: 'tf plan'
    name: 'hashicorp/terraform:1.0.0'
    entrypoint: 'sh'
    dir: 'terraform'
    args:
    -  '-c'
    -  |
        terraform plan

  - id: 'tf apply'
    name: 'hashicorp/terraform:1.0.0'
    # env:
    #   - 'BRANCH_NAME=${_BRANCH_NAME}'
    entrypoint: 'sh'
    dir: 'terraform'
    args:
    -  '-c'
    -  |
        if [[ "$BRANCH_NAME" != "main" ]]; then
          terraform apply -auto-approve -var="branch_name=$BRANCH_NAME"
        else
          exit 0
        fi

options:
  logging: CLOUD_LOGGING_ONLY